apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: roulette-analysis-pro
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/cridJR/Analise_preditiva_roleta.git
    targetRevision: feature/ia-intelligence
    path: k3s # Pasta onde estão seus arquivos YAML
  destination:
    server: https://kubernetes.default.svc
    namespace: roulette-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true